// <auto-generated />
namespace ZenithWebSite.Migrations.ZenithSociety
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RetryDummyData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RetryDummyData));
        
        string IMigrationMetadata.Id
        {
            get { return "201710150011334_Retry DummyData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
